sudo: required
services:
  - docker

before_install:
  - docker build -t name-of-container-here -f Dockerfile.dev .

script:
  - docker run -e CI=true name-of-container-here npm run test -- --watchAll=false
