sudo: required
services:
  - docker

before_install:
  - docker build -t name-of-container-here -f Dockerfile.dev .

script:
  - docker run -e CI=true name-of-container-here npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: docker-react
  env: DockerReact-env
  bucket_name: elasticbeanstalk-us-east-2-114145236294
  bucket_path: docker-react
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
